### ISSUE TITLE
Shall we use ObjectPool to to reduce gc for RedisSerializer

### ISSUE THREAD

**Issue by horizonzy** [tonivade/resp-server#83]
we use `new RedisSerializer()` when encode data.
Shall we use ObjectPool to take place of it.

**Comment by tonivade** [comment]
I don't know if I understood well, the problem is because there's a lot of RedisSerializer instances?

I'm working on a reimplementation of RedisSerializer here https://github.com/tonivade/resp-server/pull/84. Could this new implementation help in your issue?

Now is a static method, no need to create RedisSerializer instances.

**Comment by horizonzy** [comment]
> I don't know if I understood well, the problem is because there's a lot of RedisSerializer instances?
> 
> I'm working on a reimplementation of RedisSerializer here #84. Could this new implementation help in your issue?
> 
> Now is a static method, no need to create RedisSerializer instances.
RedisSerializer hold ByteBufferBuilder which hold ByteBuffer, when data output every time, it will create RedisSerializer to serialize data, we use ByteBuffer to hold temData. If the data length is large. It will occupy more memory. After we use it, it will be clean by gc.

So maybe we can create object pool like netty. Get RedisSerializer firstly, if no available RedisSerializer, create new one, after we use RedisSerializer, we put it to object pool back. So we can reuse ByteBuffer in RedisSerializer.ByteBufferBuilder.
It will reduce gc time.
